CREATE DATABASE dev WITH ENCODING 'UTF8';
CREATE DATABASE test WITH ENCODING 'UTF8';

CREATE USER dev WITH PASSWORD 'dev';

-- В базе dev
\connect dev;

GRANT ALL PRIVILEGES ON SCHEMA public TO dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dev;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO dev;

GRANT pg_read_all_data TO dev;
GRANT pg_write_all_data TO dev;
