package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const marker = "generate:reset"

type target struct {
	Name string
	// если в будущем захочешь поддержать generics — тут можно хранить сигнатуру
}

func main() {
	var (
		root    string
		pattern string
		verbose bool
	)
	flag.StringVar(&root, "root", ".", "root directory (usually module root)")
	flag.StringVar(&pattern, "pattern", "./...", "packages pattern to scan")
	flag.BoolVar(&verbose, "v", false, "verbose output")
	flag.Parse()

	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Dir:   root,
		Tests: false,
	}

	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		die("packages.Load: %v", err)
	}
	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	type pkgOut struct {
		pkgName string
		dir     string
		targets []target
	}
	outByDir := map[string]*pkgOut{}

	for _, pkg := range pkgs {
		if pkg == nil || len(pkg.Syntax) == 0 || len(pkg.GoFiles) == 0 {
			continue
		}

		if strings.Contains(pkg.PkgPath, "/cmd/reset") || strings.HasSuffix(pkg.PkgPath, "cmd/reset") {
			continue
		}

		dir := filepath.Dir(pkg.GoFiles[0])
		var targets []target

		for _, file := range pkg.Syntax {
			ast.Inspect(file, func(n ast.Node) bool {
				gen, ok := n.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					return true
				}

				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					_, ok = ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					if ts.TypeParams != nil && len(ts.TypeParams.List) > 0 {
						continue
					}

					if !hasMarker(gen.Doc) && !hasMarker(ts.Doc) {
						continue
					}

					targets = append(targets, target{Name: ts.Name.Name})
				}
				return true
			})
		}

		if len(targets) == 0 {
			continue
		}

		sort.Slice(targets, func(i, j int) bool { return targets[i].Name < targets[j].Name })

		po, ok := outByDir[dir]
		if !ok {
			po = &pkgOut{pkgName: pkg.Name, dir: dir}
			outByDir[dir] = po
		}
		po.targets = append(po.targets, targets...)
	}

	dirs := make([]string, 0, len(outByDir))
	for dir := range outByDir {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	for _, dir := range dirs {
		po := outByDir[dir]

		po.targets = dedupTargets(po.targets)

		src, err := render(po.pkgName, po.targets)
		if err != nil {
			die("render %s: %v", dir, err)
		}

		outPath := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(outPath, src, 0o644); err != nil {
			die("write %s: %v", outPath, err)
		}
		if verbose {
			fmt.Printf("generated %s (%d types)\n", outPath, len(po.targets))
		}
	}
}

func hasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		txt := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		txt = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(txt, "/*"), "*/"))
		if strings.Contains(txt, marker) {
			return true
		}
	}
	return false
}

func dedupTargets(in []target) []target {
	if len(in) == 0 {
		return in
	}
	sort.Slice(in, func(i, j int) bool { return in[i].Name < in[j].Name })
	out := make([]target, 0, len(in))
	prev := ""
	for _, t := range in {
		if t.Name == prev {
			continue
		}
		out = append(out, t)
		prev = t.Name
	}
	return out
}

func render(pkgName string, targets []target) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n")
	b.WriteString("\n")
	b.WriteString("package " + pkgName + "\n\n")

	for _, t := range targets {
		fmt.Fprintf(&b, "func (x *%s) Reset() {\n", t.Name)
		b.WriteString("\tif x == nil {\n\t\treturn\n\t}\n")
		fmt.Fprintf(&b, "\t*x = %s{}\n", t.Name)
		b.WriteString("}\n\n")
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("format.Source: %w", err)
	}
	return formatted, nil
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
