// Code generated by cmd/reset; DO NOT EDIT.

package agent

func (x *HTTPClient) Reset() {
	if x == nil {
		return
	}
	*x = HTTPClient{}
}

func (x *GRPCClient) Reset() {
	if x == nil {
		return
	}
	*x = GRPCClient{}
}