// Code generated by cmd/reset; DO NOT EDIT.

package audit

func (x *Event) Reset() {
	if x == nil {
		return
	}
	*x = Event{}
}

func (x *FileReceiver) Reset() {
	if x == nil {
		return
	}
	*x = FileReceiver{}
}

func (x *HTTPReceiver) Reset() {
	if x == nil {
		return
	}
	*x = HTTPReceiver{}
}

func (x *Publisher) Reset() {
	if x == nil {
		return
	}
	*x = Publisher{}
}
